---
name: Create & Scan SBOM
on:
  workflow_call:
    inputs:
      pre-install-python-packages:
        description: Pre-install the specified Python packages before creating the
          SBOM (this string will be directly passed to `pip install`).
        required: false
        type: string
        default: ''
permissions:
  security-events: write
  contents: write
  id-token: write
  attestations: write
jobs:
  create-and-scan-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version-file: pyproject.toml
      - name: Create lockfile and install dependencies
        run: |
          python -m pip install --upgrade poetry ${{ inputs.pre-install-python-packages }}
          python -m poetry sync
      - name: Create SBOM
        uses: anchore/sbom-action@3ad7283483fc7af8ff2b4ea19663c2d5ca935e26 # v0.24.2
        with:
          format: spdx-json
          output-file: ${{ github.event.repository.name }}-sbom.spdx.json
      - uses: actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8 # v4.2.2
        if: ${{ !(github.event.pull_request.head.repo.fork || github.event.workflow_call.pull_request.head.repo.fork) && !contains(fromJSON('["dependabot[bot]", "renovate[bot]"]'), github.actor) }}
        with:
          subject-path: ${{ github.event.repository.name }}-sbom.spdx.json
      - name: Scan SBOM
        uses: anchore/scan-action@8964e60c6fabdb85fdbbbfd9834d8f19c97a3086 # v7.4.1
        id: scan
        with:
          sbom: ${{ github.event.repository.name }}-sbom.spdx.json
          fail-build: true
          severity-cutoff: low
      - name: Scan SBOM (print results to console)
        if: ${{ always() && contains(fromJSON('["success", "failure"]'), steps.scan.outcome) }}
        uses: anchore/scan-action@8964e60c6fabdb85fdbbbfd9834d8f19c97a3086 # v7.4.1
        with:
          output-format: table
          sbom: ${{ github.event.repository.name }}-sbom.spdx.json
          fail-build: false
          severity-cutoff: low
      - name: Upload SBOM scan SARIF report as a workflow artifact
        if: ${{ always() && contains(fromJSON('["success", "failure"]'), steps.scan.outcome) }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: sarif_artifact
          path: ${{ steps.scan.outputs.sarif }}
          if-no-files-found: error
      - name: Upload SBOM scan SARIF report to GitHub UI Security tab
        if: ${{ always() && github.event_name != 'pull_request' && contains(fromJSON('["success", "failure"]'), steps.scan.outcome) }}
        uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4.37.9
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
