---
name: Auto approve Renovate PRs
on:
  pull_request_target:
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'renovate[bot]' && startsWith(github.head_ref, 'renovate/automerge/')
    steps:
      - uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363  # v4.0.0
