---
name: Auto approve Renovate/pre-commit.ci PRs
on:
  pull_request_target:
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    if: (github.actor == 'renovate[bot]' && startsWith(github.head_ref, 'renovate/automerge/'))
      || (github.actor == 'pre-commit-ci[bot]' && startsWith(github.head_ref, 'pre-commit-ci-update-config'))
    steps:
      - uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363  # v4.0.0
      - name: Enable auto-merge for pre-commit.ci autoupdate PRs
        if: github.actor == 'pre-commit-ci[bot]' && startsWith(github.head_ref, 'pre-commit-ci-update-config')
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gh pr merge --auto --merge "$PR_URL"
