---
name: Enforce Open Source Community Standards
on:
  push:
    branches: [main]
  merge_group:
  pull_request:
    branches: [main]
jobs:
  enforce-community-standards:
    uses: ./.github/workflows/_reusable-enforce-community-standards.yml
