---
name: Enforce Open Source Community Standards
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  enforce-community-standards:
    uses: tektronix/python-package-ci-cd/workflows/enforce-community-standards.yml@main
