---
name: Publish Test Results
on:
  workflow_run:
    workflows: [Test code]
    types: [completed]
jobs:
  publish-test-results:
    uses: ./.github/workflows/check-api-for-breaking-changes.yml
    with:
      operating-systems-array: '["ubuntu"]'  # this needs to match the operating-systems-array in the test-code.yml file
    permissions:
      checks: write
      pull-requests: write
