---
name: Test docs
on:
  push:
    branches: [main]
  merge_group:
  pull_request:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  test-docs:
    uses: ./.github/workflows/_reusable-test-docs.yml
    with:
      node-version: 20  # The node version needs to stay in sync with .readthedocs.yml
      python-version: pyproject.toml
      tox-env-array: '["docs", "doctests"]'
